// Generated by LiveScript 1.6.0
(function(){
  var ref$, any, all, isItNaN, types, defaultType, toString$ = {}.toString;
  ref$ = require('prelude-ls'), any = ref$.any, all = ref$.all, isItNaN = ref$.isItNaN;
  types = {
    Number: {
      typeOf: 'Number',
      validate: function(it){
        return !isItNaN(it);
      }
    },
    NaN: {
      typeOf: 'Number',
      validate: isItNaN
    },
    Int: {
      typeOf: 'Number',
      validate: function(it){
        return !isItNaN(it) && it % 1 === 0;
      }
    },
    Float: {
      typeOf: 'Number',
      validate: function(it){
        return !isItNaN(it);
      }
    },
    Date: {
      typeOf: 'Date',
      validate: function(it){
        return !isItNaN(it.getTime());
      }
    }
  };
  defaultType = {
    array: 'Array',
    tuple: 'Array'
  };
  function checkArray(input, type, options){
    return all(function(it){
      return checkMultiple(it, type.of, options);
    }, input);
  }
  function checkTuple(input, type, options){
    var i, i$, ref$, len$, types;
    i = 0;
    for (i$ = 0, len$ = (ref$ = type.of).length; i$ < len$; ++i$) {
      types = ref$[i$];
      if (!checkMultiple(input[i], types, options)) {
        return false;
      }
      i++;
    }
    return input.length <= i;
  }
  function checkFields(input, type, options){
    var inputKeys, numInputKeys, k, numOfKeys, key, ref$, types;
    inputKeys = {};
    numInputKeys = 0;
    for (k in input) {
      inputKeys[k] = true;
      numInputKeys++;
    }
    numOfKeys = 0;
    for (key in ref$ = type.of) {
      types = ref$[key];
      if (!checkMultiple(input[key], types, options)) {
        return false;
      }
      if (inputKeys[key]) {
        numOfKeys++;
      }
    }
    return type.subset || numInputKeys === numOfKeys;
  }
  function checkStructure(input, type, options){
    if (!(input instanceof Object)) {
      return false;
    }
    switch (type.structure) {
    case 'fields':
      return checkFields(input, type, options);
    case 'array':
      return checkArray(input, type, options);
    case 'tuple':
      return checkTuple(input, type, options);
    }
  }
  function check(input, typeObj, options){
    var type, structure, setting, that;
    type = typeObj.type, structure = typeObj.structure;
    if (type) {
      if (type === '*') {
        return true;
      }
      setting = options.customTypes[type] || types[type];
      if (setting) {
        return (setting.typeOf === void 8 || setting.typeOf === toString$.call(input).slice(8, -1)) && setting.validate(input);
      } else {
        return type === toString$.call(input).slice(8, -1) && (!structure || checkStructure(input, typeObj, options));
      }
    } else if (structure) {
      if (that = defaultType[structure]) {
        if (that !== toString$.call(input).slice(8, -1)) {
          return false;
        }
      }
      return checkStructure(input, typeObj, options);
    } else {
      throw new Error("No type defined. Input: " + input + ".");
    }
  }
  function checkMultiple(input, types, options){
    if (toString$.call(types).slice(8, -1) !== 'Array') {
      throw new Error("Types must be in an array. Input: " + input + ".");
    }
    return any(function(it){
      return check(input, it, options);
    }, types);
  }
  function checkArrayDetailed(input, type, options, path){
    var errors = [];
    var i;
    for (i = 0; i < input.length; i++) {
      var result = checkMultipleDetailed(input[i], type.of, options, path + '[' + i + ']');
      if (!result.result) {
        errors = errors.concat(result.errors);
      }
    }
    return {result: errors.length === 0, errors: errors};
  }

  function checkTupleDetailed(input, type, options, path){
    var errors = [];
    var i;
    for (i = 0; i < type.of.length; i++) {
      if (i >= input.length) {
        var result = checkMultipleDetailed(void 8, type.of[i], options, path + '[' + i + ']');
        if (!result.result) {
          errors.push(path + ': Tuple missing element at index ' + i);
        }
      } else {
        var result = checkMultipleDetailed(input[i], type.of[i], options, path + '[' + i + ']');
        if (!result.result) {
          errors = errors.concat(result.errors);
        }
      }
    }
    if (input.length > type.of.length) {
      errors.push(path + ': Tuple has too many elements (expected ' + type.of.length + ', got ' + input.length + ')');
    }
    return {result: errors.length === 0, errors: errors};
  }

  function checkFieldsDetailed(input, type, options, path){
    var errors = [];
    var inputKeys = {};
    var numInputKeys = 0;
    var k;
    for (k in input) {
      inputKeys[k] = true;
      numInputKeys++;
    }
    var numOfKeys = 0;
    var key;
    for (key in type.of) {
      var result = checkMultipleDetailed(input[key], type.of[key], options, path + '.' + key);
      if (!result.result) {
        errors = errors.concat(result.errors);
      }
      if (inputKeys[key]) {
        numOfKeys++;
      }
    }
    if (!type.subset && numInputKeys !== numOfKeys) {
      var extraKeys = [];
      for (k in input) {
        if (!type.of.hasOwnProperty(k)) {
          extraKeys.push(k);
        }
      }
      errors.push(path + ': Object has extra keys: ' + extraKeys.join(', '));
    }
    return {result: errors.length === 0, errors: errors};
  }

  function checkStructureDetailed(input, type, options, path){
    if (!(input instanceof Object)) {
      return {result: false, errors: [path + ': Expected Object (got ' + toString$.call(input).slice(8, -1) + ')']};
    }
    switch (type.structure) {
    case 'fields':
      return checkFieldsDetailed(input, type, options, path);
    case 'array':
      return checkArrayDetailed(input, type, options, path);
    case 'tuple':
      return checkTupleDetailed(input, type, options, path);
    }
  }

  function checkDetailed(input, typeObj, options, path){
    var type, structure, setting, that;
    path = path || 'root';
    type = typeObj.type; structure = typeObj.structure;
    if (type) {
      if (type === '*') {
        return {result: true, errors: []};
      }
      setting = options.customTypes[type] || types[type];
      if (setting) {
        var typeOk = setting.typeOf === void 8 || setting.typeOf === toString$.call(input).slice(8, -1);
        var validateOk = setting.validate(input);
        if (typeOk && validateOk) {
          return {result: true, errors: []};
        } else {
          var msg = !typeOk
            ? "Expected '" + type + "' (got " + toString$.call(input).slice(8, -1) + ")"
            : "Value failed validation for '" + type + "'";
          return {result: false, errors: [path + ': ' + msg]};
        }
      } else {
        var baseOk = type === toString$.call(input).slice(8, -1);
        if (!structure) {
          if (baseOk) return {result: true, errors: []};
          return {result: false, errors: [path + ": Expected '" + type + "' (got " + toString$.call(input).slice(8, -1) + ")"]};
        }
        var structResult = checkStructureDetailed(input, typeObj, options, path);
        if (baseOk && structResult.result) {
          return {result: true, errors: []};
        }
        var errors = [];
        if (!baseOk) errors.push(path + ": Expected '" + type + "' (got " + toString$.call(input).slice(8, -1) + ")");
        errors = errors.concat(structResult.errors);
        return {result: false, errors: errors};
      }
    } else if (structure) {
      if (that = defaultType[structure]) {
        if (that !== toString$.call(input).slice(8, -1)) {
          return {result: false, errors: [path + ': Expected ' + that + ' (got ' + toString$.call(input).slice(8, -1) + ')']};
        }
      }
      return checkStructureDetailed(input, typeObj, options, path);
    } else {
      throw new Error("No type defined. Input: " + input + ".");
    }
  }

  function checkMultipleDetailed(input, typesArr, options, path){
    if (toString$.call(typesArr).slice(8, -1) !== 'Array') {
      throw new Error("Types must be in an array. Input: " + input + ".");
    }
    var allErrors = [];
    var i;
    for (i = 0; i < typesArr.length; i++) {
      var result = checkDetailed(input, typesArr[i], options, path);
      if (result.result) {
        return {result: true, errors: []};
      }
      allErrors = allErrors.concat(result.errors);
    }
    return {result: false, errors: allErrors};
  }

  var parsedTypeCheck = function(parsedType, input, options){
    options == null && (options = {});
    if (options.customTypes == null) {
      options.customTypes = {};
    }
    return checkMultiple(input, parsedType, options);
  };

  parsedTypeCheck.detailed = function(parsedType, input, options){
    options == null && (options = {});
    if (options.customTypes == null) {
      options.customTypes = {};
    }
    return checkMultipleDetailed(input, parsedType, options, 'root');
  };

  module.exports = parsedTypeCheck;
}).call(this);
