// Generated by LiveScript 1.6.0
(function(){
  var VERSION, parseType, parsedTypeCheck, typeCheck;
  VERSION = '0.4.0';
  parseType = require('./parse-type');
  parsedTypeCheck = require('./check');
  typeCheck = function(type, input, options){
    return parsedTypeCheck(parseType(type), input, options);
  };
  var typeCheckDetailed = function(type, input, options){
    return parsedTypeCheck.detailed(parseType(type), input, options);
  };
  module.exports = {
    VERSION: VERSION,
    typeCheck: typeCheck,
    typeCheckDetailed: typeCheckDetailed,
    parsedTypeCheck: parsedTypeCheck,
    parseType: parseType
  };
}).call(this);
